### ISSUE TITLE
failed to register callback for PulseAudio signal

### ISSUE THREAD

**Issue by r10r** [mvidner/ruby-dbus#44]
Hi,

I'm trying to register a callback for a pulseaudio source device on the pulseaudio bus.
see https://gist.github.com/r10r/5496667

I get the following error:

<pre>
DBus::Error: Method "AddMatch" with signature "s" on interface "org.freedesktop.DBus" doesn't exist

    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/bus.rb:407:in `block in send_sync_or_async'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/bus.rb:633:in `call'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/bus.rb:633:in `process'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/bus.rb:580:in `send_sync'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/bus.rb:405:in `send_sync_or_async'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/introspect.rb:274:in `block (2 levels) in define_method_from_descriptor'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/bus.rb:607:in `add_match'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/introspect.rb:325:in `on_signal'
    from /var/lib/soundmaster/.gem/ruby/2.0.0/gems/ruby-dbus-0.9.1/lib/dbus/introspect.rb:455:in `on_signal'
    from (irb):145
    from /usr/bin/irb:12:in `<main>'
</pre>

Any idea what is going wrong here?

<pre>
[soundmaster@blaubeere ~]$ dbus-daemon --version
D-Bus Message Bus Daemon 1.6.8
Copyright (C) 2002, 2003 Red Hat, Inc., CodeFactory AB, and others
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</pre>

**Comment by mvidner** [comment]
Fixed now
