### ISSUE TITLE
Returning Variants in dbus_method

### ISSUE THREAD

**Issue by jameswyper** [mvidner/ruby-dbus#55]
Hello, and thanks for the work you've done on this library, it's very useful.

I am writing a dbus service for rygel, following the MediaServer2 spec. Some of the method calls required (e.g. GetAll on org.freedesktop.DBus.Properties) need to return sets of variants in an array e.g. a{sv}, so I have code like this in my org.freedesktop.DBus.Properties interface:

		dbus_method :GetAll, "in iface:s, out values:a{sv}" do |iface|
			
			rvalues = Hash.new
			case iface
			when OBJECT_IFACE
				rvalues = @propertyValuesObject2
			when CONTAINER_IFACE
				rvalues = @propertyValues
			when ""
				rvalues = @propertyValuesObject2.merge(@propertyValues)
			else
				raise DBus.error, "Could not find interface #{iface} when getting all properties"
			end
			puts rvalues.to_s
			[rvalues]
		end

@propertyValues and @propertyValuesObject2 are hashes of property name => desired value.  Elsewhere in my code the values are set either as Strings or Integers, and at the moment that's how my processing returns the message over DBus.  However I want some of the strings to be sent back over DBus as objects (signature "o" instead of "s") and some of the integers to be sent back as unsigned (signature "u" instead of "i").  
Because the message has to return an array of string / variant pairs I can't explicitly set the desired signature in the prototype.  It appears ruby-dbus is inferring the "correct" message signature to use when marshaling its reply from the object type that it marshals (String or Fixnum/Integer).  How can I get it to marshal the contents of a String as an Object, and Integer as Unsigned?

My full code is at https://github.com/jameswyper/avice by the way, but it's not anywhere near working yet (although some communication over Dbus between rygel and my server is happening)

Thanks,
James

**Comment by jreidinger** [comment]
Hi James,
it is possible, There is a trick that when you as variant pass array with two elements and first element is `DBus::Type::Type` instance then it use this type for second element of array - see source code https://github.com/mvidner/ruby-dbus/blob/master/lib/dbus/marshall.rb#L342
I cannot find now example or test that demonstrate it, but I hope I point you to right direction. quick non-tested example
```
rvalues = [DBus::type("o"), "string as object"]
rvalues = [DBus::type("u"), 256]
```

**Comment by jameswyper** [comment]
Thank you, that worked perfectly - a few quick changes and Rygel is no longer complaining about the message types not matching.  Very grateful for such a quick and helpful response!

James

**Comment by mvidner** [comment]
@jreidinger Thanks for helping out :)

@jameswyper Glad that you've been able to make it work! BTW have a look at [doc/Reference.md](http://www.rubydoc.info/github/mvidner/ruby-dbus/file/doc/Reference.md#Variants) where I tried to document this and some other less obvious things.
