### ISSUE TITLE
Deprecated use of Fixnum in Ruby 2.4

### ISSUE THREAD

**Issue by divarvel** [mvidner/ruby-dbus#66]
Since Ruby 2.4, Fixnum and Bignum are unified into Integer.

Using ruby-dbus in ruby 2.4 generates (at least) these warnings:

    ruby-dbus-0.13.0/lib/dbus/marshall.rb:299: warning: constant ::Fixnum is deprecated
    ruby-dbus-0.13.0/lib/dbus/message.rb:129: warning: constant ::Fixnum is deprecated

**Comment by nelhage-stripe** [comment]
It looks like this was fixed in https://github.com/mvidner/ruby-dbus/commit/eb6bae39eeb70806af4e82d1f4398178ba9ad01b

Are there plans for cutting a new release? It'd be nice to be able to use this on 2.4 from a rubygems release without warnings.

**Comment by franklin-stripe** [comment]
@mvidner Just wanted to bump this to see if you could build a new version of the gem with this fix? Thanks!

**Comment by mvidner** [comment]
Released: https://rubygems.org/gems/ruby-dbus/versions/0.14.0
Thanks for the ping!
