### ISSUE TITLE
Wrong alignment

### ISSUE THREAD

**Issue by MeiKatz** [mvidner/ruby-dbus#68]
Shouldn't the alignment be 2 for `INT16`?
(https://github.com/mvidner/ruby-dbus/blob/master/lib/dbus/marshall.rb#L135-L140)

**Comment by mvidner** [comment]
Oh, you are right! Thanks!

Is there a public API that fails because of this, that I should quote in the fix?

**Comment by MeiKatz** [comment]
I am not sure. I noticed it while restructuring your code base for my own needs. Maybe I will publish same in the near future and we can look what you can take for the original project.

**Comment by mvidner** [comment]
Thanks!
