### ISSUE TITLE
Remove luon.net links/mentions

### ISSUE THREAD

**Issue by paulvt** [mvidner/ruby-dbus#75]
Hi,

While Ruby D-Bus started out on our Luon infrastructure, it has long be standing on it's own here on GitHub.  As we are reorganizing our Luon infrastructure, we are going to drop a lot of services.  Because of that, I would like to ask you to remove all links to luon.net (mainly the `trac.luon.net` website and `ruby-dbus@lists.luon.net` mailing list) from the documentation/pages, as they will become broken links in the near future!

Thanks (again :)) for continuing this project!

**Comment by mvidner** [comment]
Hi Paul!

OK, replaced. Thanks for starting the project!
