### ISSUE TITLE
undefined method `singleton_class?' for DBus::Object:Class on ruby 2.0

### ISSUE THREAD

**Issue by benningm** [mvidner/ruby-dbus#78]
The `singleton_class?` is only available in ruby >= 2.1.0.

Please restore the:

```ruby
  private

  unless respond_to?(:singleton_class?)
    def singleton_class?
      ancestors.first != self
    end
  end
```

block in `lib/dbus/core_ext/class/attribute.rb`  to stay compatible with ruby 2.0.

**Comment by mvidner** [comment]
Sorry, Ruby 2.0 has been unsupported upstream for 5 years. I need to focus on the currently supported releases.

- [Ruby lifetime overview][over]
- [Specific 2.0 announcement][orig]

[over]: https://endoflife.software/programming-languages/server-side-scripting/ruby
[orig]: https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/
