### ISSUE TITLE
[Question] Problem for using variant in ApplyMonitorsConfig

### ISSUE THREAD

**Issue by rodrigosiqueira** [mvidner/ruby-dbus#82]
Hi,
I'm trying to write a simple ruby script using ruby-dbus for changing my display resolution. Usually, I use the following command:
```sh
gdbus call --session \
--dest=org.gnome.Mutter.DisplayConfig \
--object-path /org/gnome/Mutter/DisplayConfig \
--method org.gnome.Mutter.DisplayConfig.ApplyMonitorsConfig 3 1 "[(0, 0, 1, 0, true, [('HDMI-1', '1280x800@59.81082534790039', [] )] )]" "[]"
```
I know that the above command was created based on the following method [1]:
```xml
    <method name="ApplyMonitorsConfig">
      <arg name="serial" direction="in" type="u" />
      <arg name="method" direction="in" type="u" />
      <arg name="logical_monitors" direction="in" type="a(iiduba(ssa{sv}))" />
      <arg name="properties" direction="in" type="a{sv}" />
    </method>
```
Based on that I wrote a simple script that tries to reproduce part of the command described in the begging. My script looks like this:
```ruby
require "dbus"

bus = DBus::SessionBus.instance
service = bus.service("org.gnome.Mutter.DisplayConfig")
obj_conf = service.object("/org/gnome/Mutter/DisplayConfig")
obj_conf.introspect
interface = obj_conf["org.gnome.Mutter.DisplayConfig"]
serial, crtcs, outputs, modes, max_screen_width, max_screen_height = interface.GetResources

variant = DBus.variant("a{sv}", {})
logical_monitors = [0, 0, 1, 0, true, ['HDMI-1', '1280x800@59.81082534790039', variant]]

interface.ApplyMonitorsConfig(serial, 1, logical_monitors, variant)
```
However, after running the above script I got the following error:
```sh
marshall.rb:384:in `append': Struct/DE expects an Array (DBus::TypeException)
```
I also tried to remove the `DBus.variant("a{sv}", {})` and pass `{}` directly, but I got the same error.

Any ideas?

Thanks

1. https://gitlab.gnome.org/GNOME/mutter/-/blob/master/src/org.gnome.Mutter.DisplayConfig.xml#L446

**Comment by mvidner** [comment]
Hi!

Thanks for the report.

The problem is that the API expects an array of structures but you are passing only a single structure. Observe the missing brackets in the Ruby code `[0, 0, 1, 0, true, ['HDMI-1',...` compared to the gdbus call `[(0, 0, 1, 0, true, [('HDMI-1',...`

This is working for me:
```rb
...
properties = {}
monitor = ['HDMI-1', '1280x800@59.81082534790039', properties]
logical_monitor = [0, 0, 1, 0, true, [monitor]]

interface.ApplyMonitorsConfig(serial, 1, [logical_monitor], properties)
```

Now, the error message that Ruby-DBus gives you is rather cryptic. I'll look into making it more helpful.

**Comment by rodrigosiqueira** [comment]
Hi, thanks a lot for your suggestion.

Now everything works like a charm.
