### ISSUE TITLE
Better API support for read only properties

### ISSUE THREAD

**Issue by jreidinger** [mvidner/ruby-dbus#96]
Hi,
in newly added feature to support properties https://github.com/mvidner/ruby-dbus/pull/86 there is missing better support for quite common read only properties.
Basically there are two main usage of read only properties that needs to send signal.

1. just given property is changed. Now it needs to use `dbus_attr_reader`, `attr_writer` and `dbus_watcher` for that single property.
2. bunch of read only properties are changed ( like read or refresh method ). It is now supported by `dbus_attr_reader` plus call `PropertiesChanged` which is good enough.

So if it would be possible to support better use case 1. something like `dbus_ro_attr_accessor` that combines that three calls.

**Comment by jreidinger** [comment]
For me new API looks reasonable. I expect similar it will looks for rw attr in dbus? so `attr_accessor` and then `dbus_accessor`?

**Comment by mvidner** [comment]
> I expect similar it will looks for rw attr in dbus? so attr_accessor and then dbus_accessor?

Yes, and because it's a simpler case, it has a name: [`dbus_attr_accessor`](https://www.rubydoc.info/gems/ruby-dbus/0.17.0/DBus/Object#dbus_attr_accessor-class_method)
> A read-write property accessing an instance variable. A combination of `attr_accessor` and [dbus_accessor](https://www.rubydoc.info/gems/ruby-dbus/0.17.0/DBus/Object#dbus_accessor-class_method).
